read_error: show better error messages on KS 2.04+.
pt1210_file_initialize/pt1210_file_change_dir/pt1210_file_parent_dir: better
currentdir handling by trying to keep pr_CurrentDir always pointing into a
valid lock.

pt1210_file_gen_file_list: reject >=MAX_FILE_NAME_LENGTH char file names. if
we would allow MAX_FILE_NAME_LENGTH the string would not be 0 terminated, and
bad thigns would happen. I didn't increase MAX_FILE_NAME_LENGTH to avoid
breaking cache compatibility (but this is likely what we should do, but that
would require bumping version, too).